### ISSUE TITLE
update reference output file 

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Irregular_Terrains#10]
With #9, the score generated seems similar to the one expected.
Now the reference output files stored in each of the PI should be updated.

**Comment by aremazeilles** [comment]
According to https://github.com/AdrianaTorres/Irregular_Terrains/runs/1750201805 , the stored reference filenames do not have the same name as the files generated by your program:

```
 AssertionError: Element counts were not equal:
First has 1, Second has 0:  'MarginStability.yaml'
First has 0, Second has 1:  'Margin_of_Stability.yaml' : Missing generated files
```
I will adjust it, and get back to yo uwhen done.

**Comment by AdrianaTorres** [comment]
That's right, "Margin_of_stability.yaml" is an old name. I will change it now.

**Comment by AdrianaTorres** [comment]
I have just changed it. Tell me if it works now please.

**Comment by aremazeilles** [comment]
You can see above that I made a pull request (changes into a branch, ready for revision before merging within the master branch. 
And I Told you that _I will adjust it, and get back to you when done._

So I was not expecting you to do it, but wait. Could you check if the proposed changes are ok with you? Within #13

**Comment by AdrianaTorres** [comment]
Ok. I'm sorry I'm going to see the pull request.
