### ISSUE TITLE
csv file structure

### ISSUE THREAD

**Issue by aremazeilles** [AdrianaTorres/Irregular_Terrains#14]
The second issu ein the linting check is related to the csv file structure: https://github.com/AdrianaTorres/Irregular_Terrains/runs/1750201897

Effectively, if you check the file, we see:

```term
# display file content from a linux terminal
more Margin_Stability_octave/tests/data/input/COM_plano01.csv

time;x;y;z;vel_x;vel_y;vel_z;acc_x;acc_y;acc_z
3.66,76.358,1947.12,0,0,0,0,0,0,0
3.67,76.3563,1947.11,0,-0.164658,-0.989437,0,0,0,0
3.68,0,0,0,0,0,0,0,0,0
```

We see the header row is using `;` as delimiter, while the rest of the file is using `,`. This is why it complains, as 2 different delimiters are used in the file.
So I would suggest using only one, being `;`.

I can "easly" update all the csv files stored in the repository as reference files, but do you think you can, on your side, make sure the input files provided by the testbed will do the same?

**Comment by AdrianaTorres** [comment]
Yes, I will make sure the inputs provided by the testbed will be delimited by ;. Will you change it this time?

**Comment by aremazeilles** [comment]
Yep, I will change files in the repo, and open a PR for you to accept it.

**Comment by aremazeilles** [comment]
Handled in #16
